- name: svelte-kit-example
  kind: postgres
  configuration:
    connection_info:
      database_url: postgresql://postgres:postgres@host.docker.internal:5432/svelte-kit-example
      isolation_level: read-committed
      use_prepared_statements: false
  tables: "!include svelte-kit-example/tables/tables.yaml"
