-- create database "svelte-kit-example";
-- create table long_tails( tail VARCHAR, json_id integer);
-- insert into long_tails(tail, json_id) values ('front', 1);
-- insert into long_tails(tail, json_id) values ('data', 2);
-- insert into long_tails(tail, json_id) values ('api', 3);
