-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- insert into long_tails(tail, json_id) values ('front', 1);
-- insert into long_tails(tail, json_id) values ('data', 2);
-- insert into long_tails(tail, json_id) values ('api', 3);
